version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortly
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      BASE_URL: ${BASE_URL}
<<<<<<< HEAD
      DOMAIN: ${DOMAIN}
=======
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_URL_PRODUCTION: ${FRONTEND_URL_PRODUCTION}
>>>>>>> eeb58c1db84e019876d3810fc06ef77d782b9fe2
    command: ["./shortly"]

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin       
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  db-data:
