version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortly
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_URL: ${DB_URL}
      BASE_URL: ${BASE_URL}
      DOMAIN: ${DOMAIN}
      ENVIRONMENT: ${ENVIRONMENT}
    command: ["./shortly"]

volumes:
  db-data:
